apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: podinfo
    namespace: apps
spec:
  chart:
    spec:
      version: '>=1.0.0-alpha'
  values:
    - name: replicaCount
      value: 4       
    - name: ui.message
      valueFrom:
        secretKeyRef:
          name: podinfo-secrets
          key: uimessage