apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: apps
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  values:
    replicaCount: 4
  template:
    containers:
    - name: podinfo
      env: 
      - name: ECR_REGION
        value: "eu-west-1"
      - name: ECR_REGISTRY
        value: "aa"
      - name: TEST
        value: "${replicaCount}"